service: aws-node-scheduled-pokemon-finder

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: app/handler.run
    events:
      # Every day at midnight - 12am
      - schedule: cron(0 0 * * ? *)
