service: aws-node-scheduled-pokemon-finder

frameworkVersion: '2'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  cronHandler:
    handler: app/handler.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)
