export default new Map([
	['black', { hsl: 'hsl(0, 0%, 0%)', fontColor: 'var(--white)' }],
	['blue', { hsl: 'hsl(210, 100%, 56%)', fontColor: 'var(--white)' }],
	['brown', { hsl: 'hsl(25, 76%, 31%)', fontColor: 'var(--white)' }],
	['gold', { hsl: 'hsl(43, 74%, 49%)', fontColor: 'var(--black)' }],
	['gray', { hsl: 'hsl(210, 13%, 50%)', fontColor: 'var(--white)' }],
	['green', { hsl: 'hsl(146, 50%, 36%)', fontColor: 'var(--white)' }],
	['light blue', { hsl: 'hsl(195, 100%, 65%)', fontColor: 'var(--black)' }],
	['orange', { hsl: 'hsl(33, 100%, 50%)', fontColor: 'var(--black)' }],
	['pink', { hsl: 'hsl(351, 100%, 86%)', fontColor: 'var(--black)' }],
	['purple', { hsl: 'hsl(260, 60%, 65%)', fontColor: 'var(--white)' }],
	['red', { hsl: 'hsl(348, 83%, 47%)', fontColor: 'var(--white)' }],
	['white', { hsl: 'hsl(0, 0%, 96%)', fontColor: 'var(--black)' }],
	['yellow', { hsl: 'hsl(51, 100%, 50%)', fontColor: 'var(--black)' }],
])
